language: php
php:
  - 5.6
  - 7.0
before_script:
  - rm composer.lock
  - composer self-update
  - composer install
  - phpenv rehash
  - cp app/config/parameters.yml.dist app/config/parameters.yml
before_install:
  - pip install --user codecov
script:
  - php bin/console ca:c --env=test
  - php bin/console security:check
  - php ./vendor/bin/phpunit
  - php ./vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)