language: php
php:
- 5.6
- 7.0
before_script:
- rm composer.lock
- composer self-update -q
- if [ -n "GITHUB" ]; then composer config github-oauth.github.com ${GITHUB}; fi;
- composer install -n
- phpenv rehash
- cp app/config/parameters.yml.dist app/config/parameters.yml
- pip install --user codecov
script:
- php bin/console ca:c --env=test
- php bin/console security:check
- php ./vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
- codecov