language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_script:
  - rm composer.lock
  - composer self-update
  - composer install --prefer-source
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php app/console do:da:cr
  - php app/console do:mi:mi -n
  - php app/console do:fi:lo -n
script:
  - php bin/console ca:c --env=test
  - php bin/console security:check
  - php ./vendor/bin/phpunit
  - phpcs --standard=PSR1,PSR2 src -s
