app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    methods:  [GET]

intent_backend_login:
    path:   /login
    defaults: { _controller: AppBundle:Security:login }
    methods:  [GET]

intent_backend_login_check:
    path:   /login_check
    methods:  [POST]

intent_backend_logout:
    path:   /logout
    methods:  [GET]

google_api:
    resource: routing/googleApi.yml
    prefix:   /googleApi