services:
    app.googleapi.service:
        class: AppBundle\Service\GoogleApiService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%client_auth_file%'
            - '%analytics_id%'