AppBundle\Entity\GoogleApiToken:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GoogleApiTokenRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        token:
            type: string
            length: 255
    lifecycleCallbacks: {  }
